"""Seed Vietnam province/ward reference tables from the offline map datasets.

Reads frontend/public/data/vietnam-provinces.csv and vietnam-wards.csv (both
generated by scripts/generate_vietnam_admin_csv.py from the Vietnamese
provinces database) and upserts them into the vietnam_provinces and
vietnam_wards tables. Optionally loads simplified ward boundaries from the
per-province GeoJSON archives (vn-wards-{code}.geojson) produced by the same
pipeline.

Usage:
    python scripts/seed_vietnam_admin.py [--data-dir PATH] [--skip-boundaries]
"""

import argparse
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.database import db_session, get_engine, is_database_configured
from backend.models import VietnamProvince, VietnamWard
from backend.services.vietnam_admin_service import strip_diacritics

BATCH_SIZE = 500


def read_csv(path: Path) -> list[dict]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def parse_float(value: str) -> float:
    return float(value) if value not in ("", None) else 0.0


def province_row(row: dict) -> dict:
    return {
        "code": row["code"],
        "name": row["name"],
        "name_en": row["name_en"],
        "full_name": row.get("full_name") or None,
        "unit_type": row.get("unit_type") or None,
        "center_lat": parse_float(row["center_lat"]),
        "center_lng": parse_float(row["center_lng"]),
        "bbox_south": parse_float(row["bbox_south"]),
        "bbox_north": parse_float(row["bbox_north"]),
        "bbox_west": parse_float(row["bbox_west"]),
        "bbox_east": parse_float(row["bbox_east"]),
        "ward_count": int(row["ward_count"] or 0),
    }


def ward_row(row: dict) -> dict:
    ward_name = row["ward_name"]
    return {
        "ward_code": row["ward_code"],
        "province_code": row["province_code"],
        "ward_name": ward_name,
        "ward_name_en": row["ward_name_en"],
        "ward_full_name": row.get("ward_full_name") or None,
        "ward_type": row.get("ward_type") or None,
        "search_name": strip_diacritics(ward_name).lower(),
        "center_lat": parse_float(row["center_lat"]),
        "center_lng": parse_float(row["center_lng"]),
        "bbox_south": parse_float(row["bbox_south"]),
        "bbox_north": parse_float(row["bbox_north"]),
        "bbox_west": parse_float(row["bbox_west"]),
        "bbox_east": parse_float(row["bbox_east"]),
    }


def upsert_rows(session, model, rows: list[dict], key_column) -> int:
    total = 0
    for start in range(0, len(rows), BATCH_SIZE):
        batch = rows[start : start + BATCH_SIZE]
        for row in batch:
            key = row[key_column]
            existing = session.get(model, key)
            if existing is None:
                session.add(model(**row))
            else:
                for column, value in row.items():
                    setattr(existing, column, value)
        session.flush()
        total += len(batch)
    return total


def boundary_features(data_dir: Path):
    """Yield (ward_code, wkt) from every per-province boundary GeoJSON."""
    for geojson_path in sorted(data_dir.glob("vn-wards-*.geojson")):
        collection = json.loads(geojson_path.read_text(encoding="utf-8"))
        for feature in collection.get("features", []):
            properties = feature.get("properties", {})
            ward_code = properties.get("ward_code")
            geometry = feature.get("geometry")
            if not ward_code or geometry is None:
                continue
            yield str(ward_code), json.dumps(geometry, ensure_ascii=False)


def load_boundaries(session, data_dir: Path) -> tuple[int, int]:
    from sqlalchemy import text

    updated = 0
    missing = set()
    for ward_code, geojson_text in boundary_features(data_dir):
        result = session.execute(
            text(
                "UPDATE vietnam_wards "
                "SET boundary = ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON(:geojson), 4326)) "
                "WHERE ward_code = :ward_code"
            ),
            {"geojson": geojson_text, "ward_code": ward_code},
        )
        if result.rowcount:
            updated += int(result.rowcount)
        else:
            missing.add(ward_code)
    return updated, len(missing)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "frontend" / "public" / "data",
        help="Directory holding the generated CSV and GeoJSON admin files",
    )
    parser.add_argument(
        "--skip-boundaries",
        action="store_true",
        help="Skip loading ward boundary geometries",
    )
    args = parser.parse_args()

    if not is_database_configured():
        print("DATABASE_URL/POSTGRES_* is not configured; nothing to seed.")
        return 1

    provinces_path = args.data_dir / "vietnam-provinces.csv"
    wards_path = args.data_dir / "vietnam-wards.csv"
    if not provinces_path.exists() or not wards_path.exists():
        print(
            "Run scripts/generate_vietnam_admin_csv.py first; "
            f"missing {provinces_path} or {wards_path}",
            file=sys.stderr,
        )
        return 1

    engine = get_engine()
    provinces = [province_row(row) for row in read_csv(provinces_path)]
    wards = [ward_row(row) for row in read_csv(wards_path)]

    with db_session() as session:
        province_count = upsert_rows(session, VietnamProvince, provinces, "code")
        ward_count = upsert_rows(session, VietnamWard, wards, "ward_code")
        session.flush()

        boundary_count = 0
        missing_count = 0
        if not args.skip_boundaries:
            boundary_count, missing_count = load_boundaries(session, args.data_dir)

    print(f"Upserted {province_count} provinces.")
    print(f"Upserted {ward_count} wards.")
    if not args.skip_boundaries:
        print(f"Loaded {boundary_count} ward boundaries; {missing_count} unmatched.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
